export const products = [
  {
    id: 1,
    name: "Wireless Headphones",
    category: "Electronics",
    image: "/src/assets/Wireless Headphones.webp",
    price: 99.99,
    discountPrice: 79.99,
    description: "Experience high-quality sound with advanced noise cancellation technology, perfect for music lovers and professionals alike. Enjoy seamless connectivity and long battery life for uninterrupted listening.",
  },
  {
    id: 2,
    name: "Smart Watch",
    category: "Electronics",
    image: "/src/assets/smart watch.webp",
    price: 149.99,
    discountPrice: 129.99,
    description: "Stay connected and track your fitness goals with this sleek and versatile smartwatch, featuring a range of health monitoring features. Durable design for everyday use.",
  },
  {
    id: 3,
    name: "Yoga Mat",
    category: "Fitness",
    image: "/src/assets/yoga mat.jpeg",
    price: 29.99,
    description: "Enhance your yoga practice with this durable, non-slip yoga mat, designed for comfort and stability during all types of workouts. Lightweight and easy to carry.",
  },
  {
    id: 4,
    name: "Dumbbell Set",
    category: "Fitness",
    image: "/src/assets/dumbbel set.jpg",
    price: 59.99,
    discountPrice: 49.99,
    description: "Achieve your fitness goals with this adjustable dumbbell set, ideal for strength training and home workouts. Compact design for easy storage and versatility.",
  },
  {
    id: 5,
    name: "Running Shoes",
    category: "Fashion",
    image: "/src/assets/running shoes.webp",
    price: 89.99,
    discountPrice: 74.99,
    description: "Run in comfort and style with these lightweight running shoes, designed for long-distance performance and durability. Breathable material ensures maximum comfort during runs.",
  },
  {
    id: 6,
    name: "Men's T-Shirt",
    category: "Fashion",
    image: "/src/assets/mens tshirt.jpg",
    price: 19.99,
    description: "Upgrade your wardrobe with this soft cotton t-shirt, available in a variety of colors to suit any style. Perfect for casual outings or lounging at home.",
  },
  {
    id: 7,
    name: "Women's Handbag",
    category: "Fashion",
    image: "/src/assets/Women's Handbag.avif",
    price: 49.99,
    description: "Carry your essentials in style with this elegant and spacious handbag, perfect for everyday use. Features multiple compartments for better organization and convenience.",
  },
  {
    id: 8,
    name: "Coffee Maker",
    category: "Home",
    image: "/src/assets/Coffee Maker.webp",
    price: 69.99,
    discountPrice: 59.99,
    description: "Brew fresh and delicious coffee in minutes with this easy-to-use coffee maker, a must-have for coffee enthusiasts. Compact design fits any kitchen space.",
  },
  {
    id: 9,
    name: "Blender",
    category: "Home",
    image: "/src/assets/Blender.webp",
    price: 39.99,
    description: "Create smoothies, sauces, and more with this powerful and versatile blender, perfect for any kitchen. Easy to clean and comes with multiple speed settings.",
  },
  {
    id: 10,
    name: "Desk Lamp",
    category: "Home",
    image: "/src/assets/Desk Lamp.webp",
    price: 24.99,
    description: "Illuminate your workspace with this modern LED desk lamp, featuring adjustable brightness for optimal lighting. Energy-efficient and stylish design complements any decor.",
  },
  {
    id: 11,
    name: "Cookbook",
    category: "Books",
    image: "/src/assets/Cookbook.jpg",
    price: 14.99,
    description: "Explore a world of flavors with this comprehensive cookbook, filled with delicious recipes for every occasion. Includes step-by-step instructions and vibrant photographs.",
  },
  {
    id: 12,
    name: "Mystery Novel",
    category: "Books",
    image: "/src/assets/Mystery Novel.avif",
    price: 9.99,
    description: "Dive into a thrilling story full of suspense and unexpected twists with this captivating mystery novel. Perfect for fans of crime and detective fiction.",
  },
  {
    id: 13,
    name: "Wireless Mouse",
    category: "Electronics",
    image: "/src/assets/Wireless Mouse.jpeg",
    price: 19.99,
    description: "Work efficiently with this ergonomic wireless mouse, designed for comfort and long battery life. Smooth tracking and responsive clicks for seamless navigation.",
  },
  {
    id: 14,
    name: "Bluetooth Speaker",
    category: "Electronics",
    image: "/src/assets/Bluetooth Speaker.webp",
    price: 59.99,
    description: "Enjoy rich bass and clear sound with this portable Bluetooth speaker, perfect for any occasion. Long-lasting battery and compact design for easy portability.",
  },
  {
    id: 15,
    name: "Laptop Stand",
    category: "Electronics",
    image: "/src/assets/Laptop Stand.jpg",
    price: 29.99,
    description: "Improve your posture and work comfortably with this adjustable laptop stand, suitable for all devices. Lightweight and foldable for easy transport.",
  },
  {
    id: 16,
    name: "Resistance Bands",
    category: "Fitness",
    image: "https://via.placeholder.com/300x300?text=Resistance+Bands",
    price: 15.99,
    description: "Great for strength and flexibility training. Durable and versatile, these bands are perfect for a variety of exercises, from stretching to resistance workouts.",
  },
  {
    id: 17,
    name: "Foam Roller",
    category: "Fitness",
    image: "https://via.placeholder.com/300x300?text=Foam+Roller",
    price: 22.99,
    description: "Ideal for muscle recovery and massage. This foam roller helps relieve tension and improve flexibility, making it a must-have for fitness enthusiasts.",
  },
  {
    id: 18,
    name: "Leather Jacket",
    category: "Fashion",
    image: "https://via.placeholder.com/300x300?text=Leather+Jacket",
    price: 129.99,
    description: "Classic leather jacket for cool weather. Stylish and durable, this jacket is a timeless addition to any wardrobe, perfect for casual or formal occasions.",
  },
  {
    id: 19,
    name: "Sunglasses",
    category: "Fashion",
    image: "https://via.placeholder.com/300x300?text=Sunglasses",
    price: 39.99,
    description: "UV protection with stylish frames. These sunglasses combine fashion and functionality, making them an essential accessory for sunny days.",
  },
  {
    id: 20,
    name: "Vacuum Cleaner",
    category: "Home",
    image: "https://via.placeholder.com/300x300?text=Vacuum+Cleaner",
    price: 89.99,
    description: "Powerful suction for deep cleaning. This vacuum cleaner is designed to tackle dirt and debris on various surfaces, ensuring a spotless home.",
  },
  {
    id: 21,
    name: "Wall Art Canvas",
    category: "Home",
    image: "https://via.placeholder.com/300x300?text=Wall+Art",
    price: 34.99,
    description: "Decorative canvas for living room or office.",
  },
  {
    id: 24,
    name: "Gaming Keyboard",
    category: "Electronics",
    image: "https://via.placeholder.com/300x300?text=Gaming+Keyboard",
    price: 79.99,
    description: "RGB backlit keyboard for gaming enthusiasts.",
  },
  {
    id: 25,
    name: "Pull-Up Bar",
    category: "Fitness",
    image: "https://via.placeholder.com/300x300?text=Pull-Up+Bar",
    price: 45.99,
    description: "Sturdy doorframe bar for upper body workouts.",
  },
  {
    id: 26,
    name: "Track Pants",
    category: "Fashion",
    image: "https://via.placeholder.com/300x300?text=Track+Pants",
    price: 29.99,
    description: "Comfortable and breathable fabric.",
  },
  {
    id: 27,
    name: "Essential Oil Diffuser",
    category: "Home",
    image: "https://via.placeholder.com/300x300?text=Diffuser",
    price: 25.99,
    description: "Add fragrance and calm to your space.",
  },
  {
    id: 29,
    name: "Electric Toothbrush",
    category: "Electronics",
    image: "https://via.placeholder.com/300x300?text=Electric+Toothbrush",
    price: 49.99,
    description: "Deep clean with advanced brushing technology.",
  },
  {
    id: 30,
    name: "Compression Sleeves",
    category: "Fitness",
    image: "https://via.placeholder.com/300x300?text=Compression+Sleeves",
    price: 17.99,
    description: "Support your joints during workouts.",
  },
  {
    id: 31,
    name: "Smartphone Stand",
    category: "Electronics",
    image: "https://via.placeholder.com/300x300?text=Smartphone+Stand",
    price: 10.0,
    description: "Convenient and adjustable for desk use.",
  },
  {
    id: 32,
    name: "Electric Kettle",
    category: "Fitness",
    image: "https://via.placeholder.com/300x300?text=Electric+Kettle",
    price: 12.5,
    description: "Boils water quickly and safely.",
  },
  {
    id: 33,
    name: "Yoga Block",
    category: "Fashion",
    image: "https://via.placeholder.com/300x300?text=Yoga+Block",
    price: 15.0,
    description: "Sturdy foam block for yoga poses.",
  },
  {
    id: 34,
    name: "Wireless Charger",
    category: "Home",
    image: "https://via.placeholder.com/300x300?text=Wireless+Charger",
    price: 17.5,
    description: "Fast charging pad for smartphones.",
  },
  {
    id: 36,
    name: "Tote Bag",
    category: "Electronics",
    image: "https://via.placeholder.com/300x300?text=Tote+Bag",
    price: 22.5,
    description: "Eco-friendly fabric and spacious interior.",
  },
  {
    id: 37,
    name: "Graphic Hoodie",
    category: "Fitness",
    image: "https://via.placeholder.com/300x300?text=Graphic+Hoodie",
    price: 25.0,
    description: "Trendy design with warm fleece inside.",
  },
  {
    id: 38,
    name: "LED Strip Lights",
    category: "Fashion",
    image: "https://via.placeholder.com/300x300?text=LED+Strip+Lights",
    price: 27.5,
    description: "Colorful lighting for ambiance and mood.",
  },
  {
    id: 39,
    name: "Water Bottle",
    category: "Home",
    image: "https://via.placeholder.com/300x300?text=Water+Bottle",
    price: 30.0,
    description: "Insulated bottle to keep drinks cold or hot.",
  },
  {
    id: 41,
    name: "Smart Light Bulb",
    category: "Home",
    image: "https://via.placeholder.com/300x300?text=Smart+Bulb",
    price: 19.99,
    description: "Control brightness and color via app or voice.",
  },
  {
    id: 42,
    name: "Action Camera",
    category: "Electronics",
    image: "https://via.placeholder.com/300x300?text=Action+Camera",
    price: 99.99,
    description: "Capture adventures in high-definition.",
  },
  {
    id: 43,
    name: "Fitness Tracker",
    category: "Fitness",
    image: "https://via.placeholder.com/300x300?text=Fitness+Tracker",
    price: 59.99,
    description: "Monitor steps, heart rate, and sleep.",
  },
  {
    id: 44,
    name: "Denim Jeans",
    category: "Fashion",
    image: "https://via.placeholder.com/300x300?text=Denim+Jeans",
    price: 49.99,
    description: "Classic fit with modern style.",
  },
  {
    id: 45,
    name: "Standing Desk",
    category: "Home",
    image: "https://via.placeholder.com/300x300?text=Standing+Desk",
    price: 199.99,
    description: "Adjustable height for healthy posture.",
  },
  {
    id: 46,
    name: "Wireless Earbuds",
    category: "Electronics",
    image: "https://via.placeholder.com/300x300?text=Wireless+Earbuds",
    price: 69.99,
    description: "Crystal-clear audio with compact design.",
  },
  {
    id: 47,
    name: "Massage Gun",
    category: "Fitness",
    image: "https://via.placeholder.com/300x300?text=Massage+Gun",
    price: 89.99,
    description: "Relieve sore muscles with deep tissue therapy.",
  },
  {
    id: 48,
    name: "Winter Coat",
    category: "Fashion",
    image: "https://via.placeholder.com/300x300?text=Winter+Coat",
    price: 129.99,
    description: "Warm and stylish for cold weather.",
  },
  {
    id: 49,
    name: "Air Fryer",
    category: "Home",
    image: "https://via.placeholder.com/300x300?text=Air+Fryer",
    price: 99.99,
    description: "Healthier cooking with less oil.",
  },
  {
    id: 51,
    name: "Power Bank",
    category: "Electronics",
    image: "https://via.placeholder.com/300x300?text=Power+Bank",
    price: 34.99,
    description: "Charge your devices on the go.",
  },
  {
    id: 52,
    name: "Push-Up Bars",
    category: "Fitness",
    image: "https://via.placeholder.com/300x300?text=Push-Up+Bars",
    price: 18.99,
    description: "Enhance your home push-up routine.",
  },
  {
    id: 53,
    name: "Casual Sneakers",
    category: "Fashion",
    image: "https://via.placeholder.com/300x300?text=Casual+Sneakers",
    price: 59.99,
    description: "Everyday shoes with comfort and style.",
  },
  {
    id: 54,
    name: "Robot Vacuum",
    category: "Home",
    image: "https://via.placeholder.com/300x300?text=Robot+Vacuum",
    price: 149.99,
    description: "Smart cleaning while you're away.",
  },
  {
    id: 56,
    name: "Noise-Canceling Headphones",
    category: "Electronics",
    image: "https://via.placeholder.com/300x300?text=Noise+Canceling+Headphones",
    price: 149.99,
    description: "Immerse yourself in uninterrupted sound.",
  },
  {
    id: 57,
    name: "Jump Rope",
    category: "Fitness",
    image: "https://via.placeholder.com/300x300?text=Jump+Rope",
    price: 9.99,
    description: "Cardio-friendly rope for all fitness levels.",
  },
  {
    id: 58,
    name: "Flannel Shirt",
    category: "Fashion",
    image: "https://via.placeholder.com/300x300?text=Flannel+Shirt",
    price: 35.99,
    description: "Comfortable and warm, perfect for fall.",
  },
  {
    id: 59,
    name: "Espresso Machine",
    category: "Home",
    image: "https://via.placeholder.com/300x300?text=Espresso+Machine",
    price: 179.99,
    description: "Barista-quality espresso at home.",
  }
];

