export const products = [
  {
    id: 1,
    name: "Wireless Headphones",
    category: "Electronics",
    image: "/src/assets/Wireless Headphones.webp",
    price: 99.99,
    discountPrice: 79.99,
    description: "Experience high-quality sound with advanced noise cancellation technology, perfect for music lovers and professionals alike. Enjoy seamless connectivity and long battery life for uninterrupted listening.",
  },
  {
    id: 2,
    name: "Smart Watch",
    category: "Electronics",
    image: "/src/assets/smart watch.webp",
    price: 149.99,
    discountPrice: 129.99,
    description: "Stay connected and track your fitness goals with this sleek and versatile smartwatch, featuring a range of health monitoring features. Durable design for everyday use.",
  },
  {
    id: 3,
    name: "Yoga Mat",
    category: "Fitness",
    image: "/src/assets/yoga mat.jpeg",
    price: 29.99,
    description: "Enhance your yoga practice with this durable, non-slip yoga mat, designed for comfort and stability during all types of workouts. Lightweight and easy to carry.",
  },
  {
    id: 4,
    name: "Dumbbell Set",
    category: "Fitness",
    image: "/src/assets/dumbbel set.jpg",
    price: 59.99,
    discountPrice: 49.99,
    description: "Achieve your fitness goals with this adjustable dumbbell set, ideal for strength training and home workouts. Compact design for easy storage and versatility.",
  },
  {
    id: 5,
    name: "Running Shoes",
    category: "Fashion",
    image: "/src/assets/running shoes.webp",
    price: 89.99,
    discountPrice: 74.99,
    description: "Run in comfort and style with these lightweight running shoes, designed for long-distance performance and durability. Breathable material ensures maximum comfort during runs.",
  },
  {
    id: 6,
    name: "Men's T-Shirt",
    category: "Fashion",
    image: "/src/assets/mens tshirt.jpg",
    price: 19.99,
    description: "Upgrade your wardrobe with this soft cotton t-shirt, available in a variety of colors to suit any style. Perfect for casual outings or lounging at home.",
  },
  {
    id: 7,
    name: "Women's Handbag",
    category: "Fashion",
    image: "/src/assets/Women's Handbag.avif",
    price: 49.99,
    description: "Carry your essentials in style with this elegant and spacious handbag, perfect for everyday use. Features multiple compartments for better organization and convenience.",
  },
  {
    id: 8,
    name: "Coffee Maker",
    category: "Home",
    image: "/src/assets/Coffee Maker.webp",
    price: 69.99,
    discountPrice: 59.99,
    description: "Brew fresh and delicious coffee in minutes with this easy-to-use coffee maker, a must-have for coffee enthusiasts. Compact design fits any kitchen space.",
  },
  {
    id: 9,
    name: "Blender",
    category: "Home",
    image: "/src/assets/Blender.webp",
    price: 39.99,
    description: "Create smoothies, sauces, and more with this powerful and versatile blender, perfect for any kitchen. Easy to clean and comes with multiple speed settings.",
  },
  {
    id: 10,
    name: "Desk Lamp",
    category: "Home",
    image: "/src/assets/Desk Lamp.webp",
    price: 24.99,
    description: "Illuminate your workspace with this modern LED desk lamp, featuring adjustable brightness for optimal lighting. Energy-efficient and stylish design complements any decor.",
  },
  {
    id: 11,
    name: "Cookbook",
    category: "Books",
    image: "/src/assets/Cookbook.jpg",
    price: 14.99,
    description: "Explore a world of flavors with this comprehensive cookbook, filled with delicious recipes for every occasion. Includes step-by-step instructions and vibrant photographs.",
  },
  {
    id: 12,
    name: "Mystery Novel",
    category: "Books",
    image: "/src/assets/Mystery Novel.avif",
    price: 9.99,
    description: "Dive into a thrilling story full of suspense and unexpected twists with this captivating mystery novel. Perfect for fans of crime and detective fiction.",
  },
  {
    id: 13,
    name: "Wireless Mouse",
    category: "Electronics",
    image: "/src/assets/Wireless Mouse.jpeg",
    price: 19.99,
    description: "Work efficiently with this ergonomic wireless mouse, designed for comfort and long battery life. Smooth tracking and responsive clicks for seamless navigation.",
  },
  {
    id: 14,
    name: "Bluetooth Speaker",
    category: "Electronics",
    image: "/src/assets/Bluetooth Speaker.webp",
    price: 59.99,
    description: "Enjoy rich bass and clear sound with this portable Bluetooth speaker, perfect for any occasion. Long-lasting battery and compact design for easy portability.",
  },
  {
    id: 15,
    name: "Laptop Stand",
    category: "Electronics",
    image: "/src/assets/Laptop Stand.jpg",
    price: 29.99,
    description: "Improve your posture and work comfortably with this adjustable laptop stand, suitable for all devices. Lightweight and foldable for easy transport.",
  },
  {
    id: 16,
    name: "Resistance Bands",
    category: "Fitness",
    image: "/src/assets/Resistance Bands.jpg",
    price: 15.99,
    description: "Great for strength and flexibility training. Durable and versatile, these bands are perfect for a variety of exercises, from stretching to resistance workouts.",
  },
  {
    id: 17,
    name: "Foam Roller",
    category: "Fitness",
    image: "/src/assets/Foam Roller.jpg",
    price: 22.99,
    description: "Ideal for muscle recovery and massage. This foam roller helps relieve tension and improve flexibility, making it a must-have for fitness enthusiasts.",
  },
  {
    id: 18,
    name: "Leather Jacket",
    category: "Fashion",
    image: "/src/assets/Leather Jacket.jpeg",
    price: 129.99,
    description: "Classic leather jacket for cool weather. Stylish and durable, this jacket is a timeless addition to any wardrobe, perfect for casual or formal occasions.",
  },
  {
    id: 19,
    name: "Sunglasses",
    category: "Fashion",
    image: "/src/assets/Sunglasses.avif",
    price: 39.99,
    description: "UV protection with stylish frames. These sunglasses combine fashion and functionality, making them an essential accessory for sunny days.",
  },
  {
    id: 20,
    name: "Vacuum Cleaner",
    category: "Home",
    image: "/src/assets/Vacuum Cleaner.webp",
    price: 89.99,
    description: "Powerful suction for deep cleaning. This vacuum cleaner is designed to tackle dirt and debris on various surfaces, ensuring a spotless home.",
  },
  {
    id: 21,
    name: "Wall Art Canvas",
    category: "Home",
    image: "/src/assets/Wall Art Canvas.webp",
    price: 34.99,
    description: "Decorative canvas for living room or office.",
  },
  {
    id: 22,
    name: "Gaming Keyboard",
    category: "Electronics",
    image: "/src/assets/Gaming Keyboard.webp",
    price: 79.99,
    description: "RGB backlit keyboard for gaming enthusiasts.",
  },
  {
    id: 23,
    name: "Pull-Up Bar",
    category: "Fitness",
    image: "/src/assets/Pull-Up Bar.jpg",
    price: 45.99,
    description: "Sturdy doorframe bar for upper body workouts.",
  },
  {
    id: 24,
    name: "Track Pants",
    category: "Fashion",
    image: "/src/assets/Track Pants.webp",
    price: 29.99,
    description: "Comfortable and breathable fabric.",
  },
  {
    id: 25,
    name: "Essential Oil Diffuser",
    category: "Home",
    image: "/src/assets/Essential Oil Diffuser.jpg",
    price: 25.99,
    description: "Add fragrance and calm to your space.",
  },
  {
    id: 26,
    name: "Electric Toothbrush",
    category: "Electronics",
    image: "/src/assets/Electric Toothbrush.webp",
    price: 49.99,
    description: "Deep clean with advanced brushing technology.",
  },
  {
    id: 27,
    name: "Compression Sleeves",
    category: "Fitness",
    image: "/src/assets/Compression Sleeves.jpg",
    price: 17.99,
    description: "Support your joints during workouts.",
  },
  {
    id: 28,
    name: "Smartphone Stand",
    category: "Electronics",
    image: "/src/assets/Smartphone Stand.jpg",
    price: 10.0,
    description: "Convenient and adjustable for desk use.",
  },
  {
    id: 29,
    name: "Electric Kettle",
    category: "Fitness",
    image: "/src/assets/Electric Kettle.webp",
    price: 12.5,
    description: "Boils water quickly and safely.",
  },
  {
    id: 30,
    name: "Yoga Block",
    category: "Fashion",
    image: "/src/assets/Yoga Block.jpg",
    price: 15.0,
    description: "Sturdy foam block for yoga poses.",
  },
  {
    id: 31,
    name: "Wireless Charger",
    category: "Home",
    image: "./src/assets/Wireless Charger.webp",
    price: 17.5,
    description: "Fast charging pad for smartphones.",
  },
  {
    id: 32,
    name: "Tote Bag",
    category: "Electronics",
    image: "./src/assets/Tote Bag.webp",
    price: 22.5,
    description: "Eco-friendly fabric and spacious interior.",
  },
  {
    id: 33,
    name: "Graphic Hoodie",
    category: "Fitness",
    image: "./src/assets/Graphic Hoodie.webp",
    price: 25.0,
    description: "Trendy design with warm fleece inside.",
  },
  {
    id: 34,
    name: "LED Strip Lights",
    category: "Fashion",
    image: "./src/assets/LED Strip Lights.jpg",
    price: 27.5,
    description: "Colorful lighting for ambiance and mood.",
  },
  {
    id: 35,
    name: "Water Bottle",
    category: "Home",
    image: "./src/assets/Water Bottle.jpg",
    price: 30.0,
    description: "Insulated bottle to keep drinks cold or hot.",
  },
  {
    id: 36,
    name: "Smart Light Bulb",
    category: "Home",
    image: "./src/assets/Smart Light Bulb.jpg",
    price: 19.99,
    description: "Control brightness and color via app or voice.",
  },
  {
    id: 37,
    name: "Action Camera",
    category: "Electronics",
    image: "./src/assets/Action Camera.avif",
    price: 99.99,
    description: "Capture adventures in high-definition.",
  },
  {
    id: 38,
    name: "Fitness Tracker",
    category: "Fitness",
    image: "./src/assets/Fitness Tracker.jpg",
    price: 59.99,
    description: "Monitor steps, heart rate, and sleep.",
  },
  {
    id: 39,
    name: "Denim Jeans",
    category: "Fashion",
    image: "./src/assets/Denim Jeans.jpg",
    price: 49.99,
    description: "Classic fit with modern style.",
  },
  {
    id: 40,
    name: "Standing Desk",
    category: "Home",
    image: "./src/assets/Standing Desk.jpg",
    price: 199.99,
    description: "Adjustable height for healthy posture.",
  },
  {
    id: 41,
    name: "Wireless Earbuds",
    category: "Electronics",
    image: "./src/assets/Wireless Earbuds.webp",
    price: 69.99,
    description: "Crystal-clear audio with compact design.",
  },
  {
    id: 42,
    name: "Massage Gun",
    category: "Fitness",
    image: "https://via.placeholder.com/300x300?text=Massage+Gun",
    price: 89.99,
    description: "Relieve sore muscles with deep tissue therapy.",
  },
  {
    id: 43,
    name: "Winter Coat",
    category: "Fashion",
    image: "./src/assets/Winter Coat.avif",
    price: 129.99,
    description: "Warm and stylish for cold weather.",
  },
  {
    id: 44,
    name: "Air Fryer",
    category: "Home",
    image: "./src/assets/Air Fryer.png",
    price: 99.99,
    description: "Healthier cooking with less oil.",
  },
  {
    id: 45,
    name: "Power Bank",
    category: "Electronics",
    image: "./src/assets/Power Bank.webp",
    price: 34.99,
    description: "Charge your devices on the go.",
  },
  {
    id: 46,
    name: "Push-Up Bars",
    category: "Fitness",
    image: "./src/assets/Push-Up Bars.png",
    price: 18.99,
    description: "Enhance your home push-up routine.",
  },
  {
    id: 47,
    name: "Casual Sneakers",
    category: "Fashion",
    image: "./src/assets/Casual Sneakers.webp",
    price: 59.99,
    description: "Everyday shoes with comfort and style.",
  },
  {
    id: 48,
    name: "Robot Vacuum",
    category: "Home",
    image: "./src/assets/Robot Vacuum.webp",
    price: 149.99,
    description: "Smart cleaning while you're away.",
  },
  {
    id: 49,
    name: "Noise-Canceling Headphones",
    category: "Electronics",
    image: "./src/assets/Noise-Canceling Headphones.avif",
    price: 149.99,
    description: "Immerse yourself in uninterrupted sound.",
  },
  {
    id: 50,
    name: "Jump Rope",
    category: "Fitness",
    image: "./src/assets/Jump Rope.webp",
    price: 9.99,
    description: "Cardio-friendly rope for all fitness levels.",
  },
  {
    id: 51,
    name: "Flannel Shirt",
    category: "Fashion",
    image: "./src/assets/Flannel Shirt.webp",
    price: 35.99,
    description: "Comfortable and warm, perfect for fall.",
  },
  {
    id: 52,
    name: "Espresso Machine",
    category: "Home",
    image: "./src/assets/Espresso Machine.jpeg",
    price: 179.99,
    description: "Barista-quality espresso at home.",
  },

  {
    id: 53,
    name: "Bluetooth Headset",
    category: "Electronics",
    image: "./src/assets/Bluetooth Headset.webp",
    price: 44.99,
    description: "Hands-free calls and music with clear sound quality. Lightweight and comfortable for extended use, featuring noise-cancellation and a long-lasting battery for uninterrupted listening all day long."
  },
  {
    id: 54,
    name: "Balance Ball",
    category: "Fitness",
    image: "./src/assets/Balance Ball.jpg",
    price: 29.99,
    description: "Improve core strength and stability exercises. Ideal for yoga, pilates, and rehabilitation. Anti-burst material ensures safety while enhancing posture, balance, and muscle engagement effectively."
  },
  {
    id: 55,
    name: "Graphic T-Shirt",
    category: "Fashion",
    image: "./src/assets/Graphic T-Shirt.jpg",
    price: 21.99,
    description: "Eye-catching designs made with soft cotton fabric. Perfect for casual wear or layering. Breathable material keeps you cool while adding personality to your everyday outfit."
  },
  {
    id: 56,
    name: "Portable Projector",
    category: "Electronics",
    image: "./src/assets/Portable Projector.webp",
    price: 129.99,
    description: "Big screen entertainment from a compact device. Easy to carry, perfect for movie nights or presentations. Connects to smartphones, laptops, and consoles via HDMI or USB."
  },
  {
    id: 57,
    name: "Digital Alarm Clock",
    category: "Home",
    image: "./src/assets/Digital Alarm Clock.jpg",
    price: 19.99,
    description: "Wake up on time with this sleek, LED alarm clock. Features adjustable brightness, snooze function, and USB charging port to power devices while you sleep."
  },

  {
    id: 58,
    name: "Sports Bra",
    category: "Fashion",
    image: "./src/assets/Sports Bra.jpg",
    price: 27.99,
    description: "Supportive and breathable for intense workouts. Designed with moisture-wicking fabric, wide straps, and a snug fit to ensure comfort, flexibility, and confidence during any activity."
  },
  {
    id: 59,
    name: "Wireless Keyboard",
    category: "Electronics",
    image: "./src/assets/Wireless Keyboard.jpg",
    price: 39.99,
    description: "Compact, cable-free typing experience. Sleek design with responsive keys, long battery life, and multi-device compatibility for productivity at home, in the office, or on the go."
  },
  {
    id: 60,
    name: "Mini Fridge",
    category: "Home",
    image: "./src/assets/Mini Fridge.jpg",
    price: 109.99,
    description: "Compact cooling for bedrooms or dorm rooms. Energy-efficient with adjustable temperature settings, removable shelves, and quiet operation. Great for drinks, snacks, and skincare products."
  },
  {
    id: 61,
    name: "Notebook Set",
    category: "Books",
    image: "./src/assets/Notebook Set.jpg",
    price: 14.99,
    description: "Stylish notebooks for journaling or notes. Includes various page types, sturdy covers, and smooth paper ideal for writing, sketching, planning, or organizing your daily thoughts."
  },
  {
    id: 62,
    name: "Fitness Ball Chair",
    category: "Fitness",
    image: "./src/assets/Fitness Ball Chair.jpg",
    price: 54.99,
    description: "Ergonomic chair alternative that supports posture. Encourages active sitting to engage core muscles, reduce back pain, and promote better alignment during work or relaxation hours."
  },
  
  {
    id: 63,
    name: "Rain Jacket",
    category: "Fashion",
    image: "./src/assets/Rain Jacket.jpg",
    price: 69.99,
    description: "Water-resistant and windproof for rainy days. Lightweight and breathable design with adjustable hood and pockets. Keeps you dry and stylish during unpredictable weather."
  },
  {
    id: 64,
    name: "Scented Candles",
    category: "Home",
    image: "./src/assets/Scented Candles.jpg",
    price: 24.99,
    description: "Relaxing aromas for a cozy atmosphere. Made with natural soy wax and essential oils, ideal for meditation, sleep, or adding charm to any room."
  },
  {
    id: 65,
    name: "Kindle Case",
    category: "Electronics",
    image: "./src/assets/Kindle Case.webp",
    price: 15.99,
    description: "Protect your e-reader with style. Slim, durable, and lightweight with magnetic closure. Prevents scratches, dents, and dust while keeping your Kindle safe and secure."
  },
  {
    id: 66,
    name: "Adjustable Ankle Weights",
    category: "Fitness",
    image: "./src/assets/Ankle Weights.jpg",
    price: 23.99,
    description: "Increase resistance and improve workouts. Fully adjustable straps ensure a snug fit. Perfect for walking, jogging, or strength training to enhance muscle tone and endurance."
  },
  {
    id: 67,
    name: "Jogger Pants",
    category: "Fashion",
    image: "./src/assets/Jogger Pants.jpg",
    price: 34.99,
    description: "Stylish comfort for workouts or casual wear. Soft, stretchy fabric and elastic cuffs offer flexibility and mobility. Great for lounging, errands, or light exercise."
  },
  {
    id: 68,
    name: "Air Purifier",
    category: "Home",
    image: "./src/assets/Air Purifier.webp",
    price: 119.99,
    description: "Clean air with advanced filtration system. Removes dust, allergens, and odors. Whisper-quiet motor and sleep mode make it ideal for bedrooms and living spaces."
  },
  {
    id: 69,
    name: "Wireless Game Controller",
    category: "Electronics",
    image: "./src/assets/Wireless Game Controller.jpg",
    price: 49.99,
    description: "Precision control for console and PC gaming. Features ergonomic grip, responsive buttons, long-range connectivity, and customizable settings to enhance your gaming experience."
  },
  {
    id: 70,
    name: "Home Workout Poster",
    category: "Fitness",
    image: "./src/assets/Home Workout Poster.jpg",
    price: 9.99,
    description: "Visual guide to popular exercises. Colorful and easy-to-follow illustrations of bodyweight workouts. Perfect for home gyms, dorms, or fitness studios to stay motivated."
  },
  {
    id: 71,
    name: "Aromatherapy Set",
    category: "Home",
    image: "./src/assets/Aromatherapy Set.jpg",
    price: 32.99,
    description: "Relax with essential oils and calming scents. Includes diffuser and therapeutic-grade oils. Promotes sleep, stress relief, and mental clarity through natural fragrance."
  },
  {
    id: 72,
    name: "Leather Wallet",
    category: "Fashion",
    image: "./src/assets/Leather Wallet.jpg",
    price: 39.99,
    description: "Slim and stylish genuine leather wallet. Multiple card slots and a secure money clip. Timeless design for everyday use or as a gift option."
  },
  {
    id: 73,
    name: "Tabletop Tripod",
    category: "Electronics",
    image: "./src/assets/Tabletop Tripod.jpg",
    price: 17.99,
    description: "Perfect for selfies, video calls, and vlogging. Compact, foldable, and compatible with phones and cameras. Offers stability and flexible angles for content creation."
  },
  {
    id: 74,
    name: "Weighted Blanket",
    category: "Home",
    image: "./src/assets/Weighted Blanket.jpg",
    price: 79.99,
    description: "Promote restful sleep with calming pressure. Evenly distributed weight helps reduce anxiety and improve sleep quality. Soft, breathable cover for year-round comfort."
  },
  {
    id: 75,
    name: "Laptop Sleeve",
    category: "Electronics",
    image: "./src/assets/Laptop Sleeve.jpg",
    price: 19.99,
    description: "Protect your laptop with padded sleeve. Slim design fits into backpacks easily. Shock-absorbing material guards against scratches, spills, and minor bumps during travel."
  },
  {
    id: 76,
    name: "Indoor Plant Set",
    category: "Home",
    image: "./src/assets/Indoor Plant Set.jpg",
    price: 29.99,
    description: "Liven up your space with easy-care greenery. Includes pots and low-maintenance plants that purify air. Great for desks, shelves, or gifting to plant lovers."
  },
  {
    id: 77,
    name: "Zip-Up Hoodie",
    category: "Fashion",
    image: "./src/assets/Zip-Up Hoodie.jpg",
    price: 42.99,
    description: "Classic style with warmth and comfort. Fleece-lined interior, adjustable hood, and front pockets. Ideal for layering during cool days or lounging indoors."
  },
  {
    id: 78,
    name: "Resistance Tube Set",
    category: "Fitness",
    image: "./src/assets/Resistance Tube Set.jpg",
    price: 26.99,
    description: "Multiple resistance levels for full-body workouts. Comes with handles, door anchor, and carrying bag. Portable and effective for strength training anywhere, anytime."
  },
  {
    id: 79,
    name: "Smart Doorbell",
    category: "Home",
    image: "./src/assets/Smart Doorbell.jpg",
    price: 89.99,
    description: "Monitor visitors with HD video and alerts. Two-way audio, night vision, and motion detection keep your home secure and accessible from your smartphone."
  },
  {
    id: 80,
    name: "Fitness Gloves",
    category: "Fitness",
    image: "./src/assets/Fitness Gloves.jpg",
    price: 12.99,
    description: "Improve grip and protect hands during workouts. Breathable, anti-slip palms reduce friction and calluses. Great for lifting, cycling, and functional training sessions."
  },
  {
    id: 81,
    name: "Travel Backpack",
    category: "Fashion",
    image: "./src/assets/Travel Backpack.jpg",
    price: 59.99,
    description: "Spacious and durable backpack for travel. Water-resistant material, multiple compartments, and padded straps offer comfort and organization for long trips or commutes."
  },
  {
    id: 82,
    name: "Bean Bag Chair",
    category: "Home",
    image: "./src/assets/Bean Bag Chair.jpg",
    price: 84.99,
    description: "Ultimate comfort for lounging and relaxation. Filled with soft memory foam, conforms to your body shape. Stylish addition to bedrooms, dorms, or gaming rooms."
  },
  {
    id: 83,
    name: "Streaming Webcam",
    category: "Electronics",
    image: "./src/assets/Streaming Webcam.jpg",
    price: 69.99,
    description: "Crystal-clear video for calls and content creation. Features auto-focus, HD resolution, and noise-reducing microphone. Plug-and-play setup for Zoom, Twitch, YouTube, and more."
  },
  {
    id: 84,
    name: "Digital Drawing Tablet",
    category: "Electronics",
    image: "./src/assets/Digital Drawing Tablet.jpg",
    price: 99.99,
    description: "Express your creativity with precision. Pressure-sensitive pen, customizable buttons, and large drawing area for digital artists, designers, and hobbyists alike."
  },
  {
    id: 85,
    name: "Silicone Baking Mats",
    category: "Home",
    image: "./src/assets/Silicone Baking Mats.jpg",
    price: 18.99,
    description: "Reusable and easy-to-clean baking surface. Non-stick, oven-safe, and eco-friendly. Ideal for baking cookies, pastries, or roasting vegetables without oils or sprays."
  },
  {
    id: 86,
    name: "Hiking Boots",
    category: "Fashion",
    image: "./src/assets/Hiking Boots.jpg",
    price: 89.99,
    description: "Sturdy and comfortable for rugged adventures. Waterproof design, grippy soles, and ankle support make them ideal for long hikes and uneven terrains."
  },
  {
    id: 87,
    name: "Kettlebell",
    category: "Fitness",
    image: "./src/assets/Kettlebell.jpg",
    price: 35.99,
    description: "Versatile tool for strength and endurance training. Ergonomic handle and balanced weight allow dynamic movements including swings, squats, and presses for full-body workouts."
  },
  {
    id: 88,
    name: "Mirror with LED Lights",
    category: "Home",
    image: "./src/assets/Mirror with LED Lights.jpg",
    price: 49.99,
    description: "Bright, clear lighting for makeup or grooming. Adjustable brightness with touch controls and sleek frame. Ideal for dressing tables or bathroom vanities."
  },
  {
    id: 89,
    name: "Wireless Presenter",
    category: "Electronics",
    image: "./src/assets/Wireless Presenter.jpg",
    price: 24.99,
    description: "Seamless presentations with laser pointer control. Includes USB receiver, intuitive buttons, and reliable wireless range. Perfect for business, teaching, or public speaking."
  },
  {
    id: 90,
    name: "Pet Bed",
    category: "Home",
    image: "./src/assets/Pet Bed.jpg",
    price: 39.99,
    description: "Cozy sleeping spot for your furry friend. Soft, washable cover and orthopedic foam base provide comfort and support for cats and dogs alike."
  },
  {
    id: 91,
    name: "Windbreaker Jacket",
    category: "Fashion",
    image: "./src/assets/Windbreaker Jacket.jpg",
    price: 54.99,
    description: "Lightweight protection from wind and rain. Stylish design with breathable lining and zippered pockets. Great for outdoor activities or casual wear."
  },
  {
    id: 92,
    name: "Core Sliders",
    category: "Fitness",
    image: "./src/assets/Core Sliders.jpg",
    price: 14.99,
    description: "Improve core strength and balance training. Dual-sided for use on carpet or hardwood. Great for low-impact, high-intensity workouts targeting abs, legs, and glutes."
  },
  {
    id: 93,
    name: "Wall Clock",
    category: "Home",
    image: "./src/assets/Wall Clock.jpg",
    price: 22.99,
    description: "Modern design that suits any room. Silent sweep mechanism, easy-to-read numbers, and durable frame. Functional decor piece for kitchens, offices, or bedrooms."
  },
  {
    id: 94,
    name: "LED Monitor Light Bar",
    category: "Electronics",
    image: "./src/assets/Monitor Light Bar.jpg",
    price: 33.99,
    description: "Enhance your workspace with eye-friendly lighting. Reduces screen glare and eye strain. USB-powered with adjustable brightness and color temperature for better focus."
  },
  {
    id: 95,
    name: "Silicone Kitchen Utensils",
    category: "Home",
    image: "./src/assets/Kitchen Utensils.jpg",
    price: 25.99,
    description: "Heat-resistant and non-stick safe tools. Includes spatulas, tongs, and spoons. Durable, dishwasher-safe, and gentle on cookware. A must-have set for modern kitchens."
  },
  {
    id: 96,
    name: "Fashion Beanie",
    category: "Fashion",
    image: "./src/assets/Fashion Beanie.jpg",
    price: 14.99,
    description: "Stay warm with this stylish knit beanie. Stretchy, soft material fits all head sizes. Pairs well with casual or outdoor winter outfits."
  },
  {
    id: 97,
    name: "Wrist Weights",
    category: "Fitness",
    image: "./src/assets/Wrist Weights.jpg",
    price: 16.99,
    description: "Add intensity to your walking or workouts. Comfortable, adjustable straps. Ideal for cardio, running, or light resistance training to enhance calorie burn."
  },
  {
    id: 98,
    name: "LED Desk Clock",
    category: "Home",
    image: "./src/assets/LED Desk Clock.jpg",
    price: 27.99,
    description: "Digital time display with modern design. Includes temperature display, alarm, and night mode. Sleek for desks, bedside tables, or offices."
  },
  {
    id: 99,
    name: "Compact Power Strip",
    category: "Electronics",
    image: "./src/assets/Power Strip.jpg",
    price: 21.99,
    description: "Multiple outlets and USB ports in one device. Surge protection included. Compact design fits on desks or travel bags for powering devices conveniently."
  },
  {
    id: 100,
    name: "Running Armband",
    category: "Fitness",
    image: "./src/assets/Running Armband.jpg",
    price: 11.99,
    description: "Secure your phone while jogging or at the gym. Adjustable strap, sweat-resistant material, and clear screen window for full device access on the go."
  }
  
  
];

